#############################################################################
# Makefile for building: stlviewer
# Generated by qmake (1.07a) (Qt 3.3.8) on: Tue Nov 12 20:34:21 2024
# Project:  stlviewer.pro
# Template: app
# Command: $(QMAKE) -o Makefile stlviewer.pro
#############################################################################

####### Compiler, tools and options

CC       = gcc
CXX      = g++
LEX      = flex
YACC     = yacc
CFLAGS   = -pipe -Wall -W -g  -D'VERSION="5.0"' -DQT_CLEAN_NAMESPACE -DQT_SHARED -DQT_NO_DEBUG
CXXFLAGS = -pipe -Wall -W -g  -D'VERSION="5.0"' -DQT_CLEAN_NAMESPACE -DQT_SHARED -DQT_NO_DEBUG
LEXFLAGS = 
YACCFLAGS= -d
INCPATH  = -I/home/sharjith/Downloads/qt-x11-free-3.3.8/mkspecs/default -I. -I. -I/home/sharjith/include -I$(QTDIR)/include -I/usr/X11R6/include -I/usr/X11R6/include
LINK     = g++
LFLAGS   =  -Wl,-rpath,$(QTDIR)/lib
LIBS     = $(SUBLIBS) -L$(QTDIR)/lib -L/usr/X11R6/lib -L/usr/X11R6/lib -L/home/sharjith/lib64 -lVKGeom -lVKGraphic -lVKCollection -lglut -lqt -lGLU -lGL -lXmu -lXext -lX11 -lm
AR       = ar cqs
RANLIB   = 
MOC      = $(QTDIR)/bin/moc
UIC      = $(QTDIR)/bin/uic
QMAKE    = qmake
TAR      = tar -cf
GZIP     = gzip -9f
COPY     = cp -f
COPY_FILE= $(COPY)
COPY_DIR = $(COPY) -r
INSTALL_FILE= $(COPY_FILE)
INSTALL_DIR = $(COPY_DIR)
DEL_FILE = rm -f
SYMLINK  = ln -sf
DEL_DIR  = rmdir
MOVE     = mv -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p

####### Output directory

OBJECTS_DIR = ./

####### Files

HEADERS = GLDisplayContext.h \
		ListIteratorOfListOfCTriFacet.h \
		ListNodeOfCTriFacet.h \
		ListOfCTriFacet.h \
		MaterialDlg.ui.h \
		MDIWindow.h \
		QGLView.h \
		StLObject.h \
		StLReader.h \
		StLViewer.h \
		StLViewerDoc.h \
		StLViewerView.h \
		TriFacet.h
SOURCES = GLDisplayContext.cpp \
		ListIteratorOfListOfCTriFacet.cpp \
		ListNodeOfCTriFacet.cpp \
		ListOfCTriFacet.cpp \
		main.cpp \
		MDIWindow.cpp \
		QGLView.cpp \
		StLObject.cpp \
		StLReader.cpp \
		StLViewer.cpp \
		StLViewerDoc.cpp \
		StLViewerView.cpp
OBJECTS = GLDisplayContext.o \
		ListIteratorOfListOfCTriFacet.o \
		ListNodeOfCTriFacet.o \
		ListOfCTriFacet.o \
		main.o \
		MDIWindow.o \
		QGLView.o \
		StLObject.o \
		StLReader.o \
		StLViewer.o \
		StLViewerDoc.o \
		StLViewerView.o \
		MaterialDlg.o
FORMS = MaterialDlg.ui
UICDECLS = MaterialDlg.h
UICIMPLS = MaterialDlg.cpp
SRCMOC   = moc_MDIWindow.cpp \
		moc_StLViewer.cpp \
		moc_StLViewerDoc.cpp \
		moc_StLViewerView.cpp \
		moc_MaterialDlg.cpp
OBJMOC = moc_MDIWindow.o \
		moc_StLViewer.o \
		moc_StLViewerDoc.o \
		moc_StLViewerView.o \
		moc_MaterialDlg.o
DIST	   = stlviewer.pro
QMAKE_TARGET = stlviewer
DESTDIR  = 
TARGET   = stlviewer

first: all
####### Implicit rules

.SUFFIXES: .c .o .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(UICDECLS) $(OBJECTS) $(OBJMOC)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(OBJCOMP) $(LIBS)

mocables: $(SRCMOC)
uicables: $(UICDECLS) $(UICIMPLS)

$(MOC): 
	( cd $(QTDIR)/src/moc && $(MAKE) )

Makefile: stlviewer.pro  /home/sharjith/Downloads/qt-x11-free-3.3.8/mkspecs/default/qmake.conf /home/sharjith/Downloads/qt-x11-free-3.3.8/lib/libqt.prl
	$(QMAKE) -o Makefile stlviewer.pro
qmake: 
	@$(QMAKE) -o Makefile stlviewer.pro

dist: 
	@mkdir -p .tmp/stlviewer && $(COPY_FILE) --parents $(SOURCES) $(HEADERS) $(FORMS) $(DIST) .tmp/stlviewer/ && $(COPY_FILE) --parents MaterialDlg.ui.h .tmp/stlviewer/ && ( cd `dirname .tmp/stlviewer` && $(TAR) stlviewer.tar stlviewer && $(GZIP) stlviewer.tar ) && $(MOVE) `dirname .tmp/stlviewer`/stlviewer.tar.gz . && $(DEL_FILE) -r .tmp/stlviewer

mocclean:
	-$(DEL_FILE) $(OBJMOC)
	-$(DEL_FILE) $(SRCMOC)

uiclean:
	-$(DEL_FILE) $(UICIMPLS) $(UICDECLS)

yaccclean:
lexclean:
clean: mocclean uiclean
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) $(TARGET)


FORCE:

####### Compile

GLDisplayContext.o: GLDisplayContext.cpp GLDisplayContext.h \
		StLViewerDoc.h \
		QGLView.h \
		StLReader.h \
		StLObject.h \
		ListOfCTriFacet.h \
		ListIteratorOfListOfCTriFacet.h \
		TriFacet.h \
		ListNodeOfCTriFacet.h

ListIteratorOfListOfCTriFacet.o: ListIteratorOfListOfCTriFacet.cpp ListIteratorOfListOfCTriFacet.h \
		ListNodeOfCTriFacet.h \
		ListOfCTriFacet.h \
		TriFacet.h

ListNodeOfCTriFacet.o: ListNodeOfCTriFacet.cpp ListNodeOfCTriFacet.h \
		TriFacet.h

ListOfCTriFacet.o: ListOfCTriFacet.cpp ListOfCTriFacet.h \
		ListNodeOfCTriFacet.h \
		TriFacet.h

main.o: main.cpp StLViewer.h \
		MDIWindow.h \
		StLViewerView.h \
		QGLView.h \
		GLDisplayContext.h \
		StLViewerDoc.h \
		StLReader.h \
		StLObject.h \
		ListOfCTriFacet.h \
		ListIteratorOfListOfCTriFacet.h \
		TriFacet.h \
		ListNodeOfCTriFacet.h

MDIWindow.o: MDIWindow.cpp MDIWindow.h \
		StLViewerView.h \
		StLViewer.h \
		QGLView.h \
		GLDisplayContext.h \
		StLViewerDoc.h \
		StLReader.h \
		StLObject.h \
		ListOfCTriFacet.h \
		ListIteratorOfListOfCTriFacet.h \
		TriFacet.h \
		ListNodeOfCTriFacet.h

QGLView.o: QGLView.cpp StLViewerDoc.h \
		QGLView.h \
		GLDisplayContext.h \
		StLReader.h \
		StLObject.h \
		ListOfCTriFacet.h \
		ListIteratorOfListOfCTriFacet.h \
		TriFacet.h \
		ListNodeOfCTriFacet.h

StLObject.o: StLObject.cpp StLViewer.h \
		StLObject.h \
		MDIWindow.h \
		StLViewerView.h \
		QGLView.h \
		GLDisplayContext.h \
		StLViewerDoc.h \
		StLReader.h \
		ListOfCTriFacet.h \
		ListIteratorOfListOfCTriFacet.h \
		TriFacet.h \
		ListNodeOfCTriFacet.h

StLReader.o: StLReader.cpp StLViewer.h \
		StLReader.h \
		MDIWindow.h \
		StLViewerView.h \
		QGLView.h \
		GLDisplayContext.h \
		StLViewerDoc.h \
		StLObject.h \
		ListOfCTriFacet.h \
		ListIteratorOfListOfCTriFacet.h \
		TriFacet.h \
		ListNodeOfCTriFacet.h

StLViewer.o: StLViewer.cpp StLViewerView.h \
		StLViewerDoc.h \
		StLViewer.h \
		res/appicon.xpm \
		res/filenew.xpm \
		res/fileopen.xpm \
		res/filesave.xpm \
		res/top.xpm \
		res/bottom.xpm \
		res/front.xpm \
		res/back.xpm \
		res/left.xpm \
		res/right.xpm \
		res/axo.xpm \
		res/reset.xpm \
		res/fitall.xpm \
		res/zoomwin.xpm \
		res/dmode.xpm \
		res/hlr.xpm \
		res/antial.xpm \
		res/stl.xpm \
		MaterialDlg.h \
		QGLView.h \
		MDIWindow.h \
		GLDisplayContext.h \
		StLReader.h \
		StLObject.h \
		ListOfCTriFacet.h \
		ListIteratorOfListOfCTriFacet.h \
		TriFacet.h \
		ListNodeOfCTriFacet.h

StLViewerDoc.o: StLViewerDoc.cpp StLViewer.h \
		StLViewerDoc.h \
		StLViewerView.h \
		MDIWindow.h \
		QGLView.h \
		GLDisplayContext.h \
		StLReader.h \
		StLObject.h \
		ListOfCTriFacet.h \
		ListIteratorOfListOfCTriFacet.h \
		TriFacet.h \
		ListNodeOfCTriFacet.h

StLViewerView.o: StLViewerView.cpp StLViewerView.h \
		StLViewerDoc.h \
		StLViewer.h \
		QGLView.h \
		MDIWindow.h \
		GLDisplayContext.h \
		StLReader.h \
		StLObject.h \
		ListOfCTriFacet.h \
		ListIteratorOfListOfCTriFacet.h \
		TriFacet.h \
		ListNodeOfCTriFacet.h

MaterialDlg.h: MaterialDlg.ui 
	$(UIC) MaterialDlg.ui -o MaterialDlg.h

MaterialDlg.cpp: MaterialDlg.h MaterialDlg.ui MaterialDlg.ui.h 
	$(UIC) MaterialDlg.ui -i MaterialDlg.h -o MaterialDlg.cpp

MaterialDlg.o: MaterialDlg.cpp MaterialDlg.ui.h \
		MaterialDlg.h

moc_MDIWindow.o: moc_MDIWindow.cpp  MDIWindow.h StLViewerView.h \
		StLViewer.h \
		QGLView.h \
		GLDisplayContext.h \
		StLViewerDoc.h \
		StLReader.h \
		StLObject.h \
		ListOfCTriFacet.h \
		ListIteratorOfListOfCTriFacet.h \
		TriFacet.h \
		ListNodeOfCTriFacet.h

moc_StLViewer.o: moc_StLViewer.cpp  StLViewer.h MDIWindow.h \
		StLViewerView.h \
		QGLView.h \
		GLDisplayContext.h \
		StLViewerDoc.h \
		StLReader.h \
		StLObject.h \
		ListOfCTriFacet.h \
		ListIteratorOfListOfCTriFacet.h \
		TriFacet.h \
		ListNodeOfCTriFacet.h

moc_StLViewerDoc.o: moc_StLViewerDoc.cpp  StLViewerDoc.h GLDisplayContext.h \
		StLReader.h \
		StLObject.h \
		QGLView.h \
		ListOfCTriFacet.h \
		ListIteratorOfListOfCTriFacet.h \
		TriFacet.h \
		ListNodeOfCTriFacet.h

moc_StLViewerView.o: moc_StLViewerView.cpp  StLViewerView.h StLViewer.h \
		QGLView.h \
		MDIWindow.h \
		GLDisplayContext.h \
		StLViewerDoc.h \
		StLReader.h \
		StLObject.h \
		ListOfCTriFacet.h \
		ListIteratorOfListOfCTriFacet.h \
		TriFacet.h \
		ListNodeOfCTriFacet.h

moc_MaterialDlg.o: moc_MaterialDlg.cpp  MaterialDlg.h 

moc_MDIWindow.cpp: $(MOC) MDIWindow.h
	$(MOC) MDIWindow.h -o moc_MDIWindow.cpp

moc_StLViewer.cpp: $(MOC) StLViewer.h
	$(MOC) StLViewer.h -o moc_StLViewer.cpp

moc_StLViewerDoc.cpp: $(MOC) StLViewerDoc.h
	$(MOC) StLViewerDoc.h -o moc_StLViewerDoc.cpp

moc_StLViewerView.cpp: $(MOC) StLViewerView.h
	$(MOC) StLViewerView.h -o moc_StLViewerView.cpp

moc_MaterialDlg.cpp: $(MOC) MaterialDlg.h
	$(MOC) MaterialDlg.h -o moc_MaterialDlg.cpp

####### Install

install:  

uninstall:  

