//############################################################################

//  Author:	Sharjith Nair
//  Email:	sharjith_ssn@hotmail.com

// Program:	OpenGL, C++ Qt StL Data File Viewer Application

//							Important Notice:

//	This Idea and the Application is Copyright(c) Sharjith Nair 2002, 2003.
//	You can freely use it as long as you credit me for it.

//	No guarantee/warranty is given on this app and I will not be responsible
//	for any damage to you, your property or any other person from using it.
//	USE IT ON YOUR OWN RISK.

//	Thankyou
//	Sharjith Nair.

//#############################################################################

#ifndef STLVIEWERDOC_H
#define STLVIEWERDOC_H

#ifdef HAVE_CONFIG_H
#include <config.h>
#endif 

// include files for QT
#include <qobject.h>
#include <qstring.h>
#include <qlist.h>

//Geometry
#include <Geometry.h>
#include <GeomException.h>
#include <Point3D.h>
#include <Vector3D.h>
#include <Line3D.h>
#include <Plane.h>

#include <MMath.h>
//Graphics
#include <GLObject.h>
#include <GLAxisSystem.h>
#include <GLTrihedron.h>
//#include "GLFont.h"
#include <BoundingBox.h>

//Display Context
#include "GLDisplayContext.h"

//StL
#include "StLReader.h"
#include "StLObject.h"

// forward declaration of the StLViewer classes
class StLViewerView;
class CGLDisplayContext;

/**	StLViewerDoc provides a document object for a document-view model.
  *
  * The StLViewerDoc class provides a document object that can be used in conjunction with the classes
  * StLViewerApp and StLViewerView to create a document-view model for MDI (Multiple Document Interface)
  * Qt 2.1 applications based on QApplication and QMainWindow as main classes and QWorkspace as MDI manager widget.
  * Thereby, the document object is created by the StLViewerApp instance (and kept in a document list) and contains
  * the document structure with the according methods for manipulating the document
  * data by StLViewerView objects. Also, StLViewerDoc contains the methods for serialization of the document data
  * from and to files.
  * @author Source Framework Automatically Generated by KDevelop, (c) The KDevelop Team. 	
  * @version KDevelop version 1.1 code generation
  */
class StLViewerDoc : public QObject
{
  Q_OBJECT

  friend class StLViewerView;

  public:
    /** Constructor for the fileclass of the application */
    StLViewerDoc();
    /** Destructor for the fileclass of the application */
    ~StLViewerDoc();

    CGLDisplayContext* GetDisplayContext() const { return dContext; }

    /** adds a view to the document which represents the document contents. Usually this is your main view. */
    void addView(StLViewerView *view);
    /** removes a view from the list of currently connected views */
    void removeView(StLViewerView *view);
		/** gets called if a view is removed or added */
		void changedViewList();
    /** returns the first view instance */
		StLViewerView* firstView(){ return pViewList->first(); };
		/** returns true, if the requested view is the last view of the document */
    bool isLastView();
    /** This method gets called when the user is about to close a frame window. It checks, if more than one view
    	* is connected to the document (then the frame can be closed), if pFrame is the last view and the document is
    	* modified, the user gets asked if he wants to save the document.
    	*/
		bool canCloseFrame(StLViewerView* pFrame);
    /** sets the modified flag for the document after a modifying action on the view connected to the document.*/
    void setModified(bool _m=true){ modified=_m; };
    /** returns if the document is modified or not. Use this to determine if your document needs saving by the user on closing.*/
    bool isModified(){ return modified; };
    /** deletes the document's contents */
    void deleteContents();
    /** initializes the document generally */
    bool newDocument();
    /** closes the acutal document */
    void closeDocument();
    /** loads the document by filename and format and emits the updateViews() signal */
    bool openDocument(const QString &filename, const char *format=0);
    /** saves the document under filename and format.*/	
    bool saveDocument(const QString &filename, const char *format=0);
    /** sets the path to the file connected with the document */
    void setPathName(const QString &name);
    /** returns the pathname of the current document file*/
    const QString& pathName() const;

    /** sets the filename of the document */
    void setTitle(const QString &title);
    /** returns the title of the document */
    const QString& title() const;

    /*Read StL File*/
    void ReadStLFile(const QString& str);
	
  public slots:
    /** calls repaint() on all views connected to the document object and is called by the view by which the document has been changed.
     * As this view normally repaints itself, it is excluded from the paintEvent.
     */
    void updateAllViews(StLViewerView *sender);
 	
  private:
    /** the modified flag of the current document */
    bool modified;
    QString m_title;
    QString m_filename;
    /** the list of the views currently connected to the document */
    QList<StLViewerView> *pViewList;	
public:
    CGLDisplayContext* dContext;
    CStLReader* m_Reader;
    CStLObject* m_stlObj;
};

#endif // STLVIEWERDOC_H
